### ISSUE TITLE
Report verifica verbale esterno 2016-12-17

### ISSUE THREAD

**Issue by BottCode** [CoCodeSWE/Docs#10]
@sime1 , la struttura del verbale rispetta le NdP, tuttavia presenta qualche sbavatura nei contenuti.
1 - Il titolo del documento ha la data sbagliata, ovvero quella del verbale interno. Lo stesso dicasi per la data di redazione.
2 - nelle informazioni generali c'è scritto durata di "11:45". In quel campo ci andrebbe la differenza tra inizio e fine, quindi 1h.
3- In "partecipanti" vanno scritti tutti coloro che hanno partecipato alla riunione, ovvero il proponente e i membri degli altri gruppi. Facendo così, si può rimuovere questa informazione dalla descrizione 2.1 .
4- In 2.1, quando si nomina il progetto d'appalto, forse è meglio metterlo tra virgolette(ma questa forse è da correggere nelle macro).
5 - In decisioni e tematiche in sospeso hai usato una notazione non coerente con le norme di progetto. Tuttavia, si può discutere di ciò andando a cambiare le NdP. @Mou95 che ne dici? Lo stesso dicasi per il nome del file. 

Marco la issue sia come "bug" (in merito alle sbavature) sia come "question" (in merito alla discussione sulle NdP).

**Comment by sime1** [comment]
1,2 chiaro, correggo
3 - Mi sono basato sul primo verbale esterno dei fellowship of the code, la versione della RP, valutata in modo positivo. Loro in partecipanti mettevano unicamente i membri del gruppo, e gli esterni venivano nominati nel sommario. Se comunque valutate che sia un errore correggo.
4 - Ditemi voi... Se in qualche occasione è possibile che utilizziamo il nome del capitolato senza le virgolette allora le metto io, altrimenti cambiamo direttamente la macro
5 - Ho provato a guardare le NdP per quanto riguarda la notazione da utilizzare nel verbale, ma ho guradato dalla parte sbagliata, quindi ho adattato la notazione utilizzata dal verbale che ho utilizzato come riferimento. Di nuovo, ditemi voi se vogliamo fare la distinzione tra verbali esterni ed interni oppure no

**Comment by BottCode** [comment]
3 - Non lo sapevo, allora forse è meglio così. Sentiamo @Mou95 .
4 - Secondo me l'uso di esse dipende dal contesto. Credo sia meglio non cambiare la macro.
5 - Aspetto il parere di @Mou95 e, al limite, creerò un poll sul gruppo Telegram per decidere insieme.

**Comment by Mou95** [comment]
3 - I partecipanti vengono intesi come membri del gruppo. Qualsiasi altra persona la inseriamo nel sommario.
4 - Sono d'accordo con @BottCode, mettiamo le vigolette quando serve senza cambiare la macro.
5 - Abbiamo deciso di utilizzare due notazioni diverse per verbali interni ed esterni:
      5.1 Per gli interni usiamo DIX.Y e SIX.Y, dove X e Y seguono e regole già scritte
      5.2 Per gli esterni usiamo DEX.Y e SEX.Y, X e Y come sopra

Aggiorniamo le norme di progetto in base a queste nuove regole.

C'è un errore nel diario delle modifiche. Deve essere ordinato per numero di versione o per date di modifica, inoltre la versione della "Corretti errori data ora e durata" deve essere 0.1.0. Puoi lasciare 0.1.1 se aggiungi il fatto che il documento è stato verificato.

**Comment by BottCode** [comment]
Inoltre questo verbale esterno è ella cartella dei documenti interni. Dovrebbe trovarsi, invece, in documenti esterni.

**Comment by sime1** [comment]
Sì me ne sono reso conto dopo. Ora l'ho spostato, ho fatto le correzioni e ho fatto il push

**Comment by Mou95** [comment]
Mi sono dimenticato di dire che i nomi dei verbali sono:
NomeVerbale_TipoVerbale_DataVerbale
 dove il tipo è E per gli esterni e I per gli interni

@BottCode li aggiorna

**Comment by BottCode** [comment]
Aggiornati, chiudo l'issue.
