### ISSUE TITLE
Subfile Latex

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#11]
Scrivendo il piano di progetto, ho visto che è possibile rendere compilabili anche i singoli file delle sezioni, quelli che poi vengono inclusi nel file completo, ed è piuttosto semplice. Basta aggiungere all'inizio dei file delle sezioni le righe 

`\documentclass[./percorso-del-file-principale.tex]{subfiles}`
`\begin{document}`

ed alla fine del file la riga

`end{document}`

L'unica modifica del template dovrebbe essere l'aggiunta di 

`\usepackage{subfiles}`

Per l'iunclusione di un sottofile creato in questo modo bisognerebe utilizzare la direttiva `\subfile{}` al posto di `\include{}`, mentre i file attuali potrebbero essere lasciati così come sono. Potrebbe essere comodo poter compilare direttamente i sottofile senza dover passare ogni volta per il documento intero.

**Comment by sosssoldi** [comment]
Mi sembra una cosa fantastica
