### ISSUE TITLE
Limite superiore numero versione

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#12]
È stato deciso di limitare superiormente il numero di versione in base al numero di revisioni. Tuttavia il numero di fasi pensate per il Piano di Progetto è superiore al numero di revisioni; è perciò possibile che il numero di volte che un documento viene approvato dal Responsabile sia maggiore del numero delle revisioni. Chiedo quindi se è possibile rimuovere tale limitazione

**Comment by BottCode** [comment]
Non mi è chiara una cosa: al termine di una fase il PdP dovrebbe essere solamente verificato e non approvato. O sbaglio?

**Comment by sime1** [comment]
I tre gruppi che ho guardato lo approvavano ogni volta. Effettivamente se i documenti cambiano il responsabile dovrebbe approvare ogni volta. Anche i Mint, che nelle norme limitavano il numero di versione come ora facciamo noi, hanno la versione 5.0.0 come versione finale di diversi documenti

**Comment by BottCode** [comment]
Ah scusa, avevo capito all'interno di una revisione e non durante tutta la durata del progetto.
In tal caso io concordo

**Comment by Mou95** [comment]
Ho tolto quel vincolo
