### ISSUE TITLE
Verifica PdP 18/12

### ISSUE THREAD

**Issue by Scramasax443** [CoCodeSWE/Docs#15]
@sime1
- Nel diario delle modifiche in 0.0.1  Brtolini --> Bertolini;
- in 1.1 Co.Codeper -->Co.Code per
- sempre in 1.1 dato che il secondo e il terzo punto dell'elenco iniziano con un articolo,è bene metterlo anche nel primo (analisi e trattamento-->l'analisi e il trattamento) o toglierlo in tutti;
-in 1.4.1 la lettera maiuscola ad inizio riga;
-in 2 l'utilizzo del corsivo nei titoli non rispetta le NdP;
-in 2.1 è ripetuto troppe volte il verbo "stendere";
- 2.1 punto 1 strumeti-->strumenti;
-2.1 punto 1 non so se la scelta degli strumenti sia definibile incrementale,sarebbe bene discuterne con gli altri membri;
-2.1 punto 3 seguanti-->seguenti;
-2.1 punto 3 analisi requisiti: verano -->verranno;
-2.1 punto 3 piano di qualifica: fissare quali sono gli standard -->fissare gli standard;
-2.1 punto 3 negli ultimi 3 punti manca il punto e virgola a fine frase;
-in 2.3 "Questo periodo comincia al termine del periodo A" cos'è il periodo A? non è stato specificato il significato di A;
-2.4.1 secondo le NdP "Revisione di progettazione" non andrebbe in grassetto,ma  effettivamente le NdP non parlano delle varie fasi: @BottCode , @Mou95 cosa dite?
-2.4.1: serve la lettera maiuscola all'inizio di ogni punto nell'elenco,non solo in alcuni;
_Edit: Effettivamente dire "in ogni punto dell'elenco" è giusto in questo caso,ma non in tutti; per riferimenti controllare le NdP a 3.1.8.2;_
 -2.4.1 terzo punto: vengo apportate -->vengono apportate;
-2.4.1 quarto punto: vocabili --> vocaboli;

Questo è tutto,chiudete pure la issue una volta risolti i problemi.

**Comment by BottCode** [comment]
2.4.1 - Ma è stata utilizzata una macro per tutte quelle parole in corsivo? Tutte quelle maiuscole nel mezzo della frase non sono grammaticamente corrette. Le NdP non dicono che vanno scritte così: io mi limiterei al solo corsivo
@Scramasax443 dice "_-2.4.1: serve la lettera maiuscola all'inizio di ogni punto nell'elenco,non solo in alcuni;_". No, è proprio l'opposto! Gli elenchi puntati sono spiegati in 3.1.8.2 delle NdP.

**Il verificatore deve controllare ed assicurare la coerenza con le NdP. È fondamentale averle a mente.**

**Comment by Scramasax443** [comment]
Purtroppo quel punto preciso delle NdP mi è sfuggito (infatto ho sbagliato anche nella stesura dello SdF),chiedo venia. Resta comunque il fatto che mischiare maiuscolo e minuscolo senza apparente motivo resta una violazione delle NdP. 
Riguardo la tua prima frase, @BottCode è vero inoltre che le NdP non descrivono lo stile delle varie revisioni e/o fasi del progetto, in quanto non rientrano in nessuna delle categorie inserite. Proporrei quindi la modifica delle NdP per precisare questo dettaglio.
