### ISSUE TITLE
Report verifica SdF del 2016-12-18

### ISSUE THREAD

**Issue by BottCode** [CoCodeSWE/Docs#16]
1 - In 2.3 e 2.4.1 ci sono elenchi puntanti non coerenti con le norme tipografiche spiegate nelle NdP. Vedere 3.1.8.2 delle NdP. In particolare, è bene correggere quello in 2.3(e quelli simili) in questo modo(visto che contiene dei nomi propri)
  ... ... ... le seguenti tecnologie: 

  - Amazon Web Services; (nel vostro manca il ";" )
  - Database No.... ;
  - HTML5, CSS3 e Javascript (per l'interfaccia con l'utente);
  - Slack (per il sistema di comunicazione);
  - Node.js o Swift (come linguaggio ... );
  - SDK Amazon Alexa o Siri (come assistente virtuale).

Quindi rimozione dei ":" di secondo livello per sostituirli con le parentesi. Nel terzo punto manca lo spazio dopo la virgola.
_Edit: in reltà mettere per la seconda volta i ":" non è sbagliato, ma meno preferibile delle parentesi._
Solo gli elenchi puntati in 3.1 sono corretti, tutti gli altri violano le NdP.
Anche l'elenco in 6.1 può andare bene.
Invece, gli elenchi tipo quello in 3.4.2 andrebbero convertiti così
    x.y.z  Titolo
        I fattori di rischio sono:
    -  collaborazione...; 
    -  ecc.

Magari nel modo che avete fatto può andare bene, ma così andiamo sul sicuro.
**Rivedere e correggere tutti gli elenchi puntanti. Documentarsi in 3.1.8.2 delle NdP**.

2 - In 3.1 manca la virgola prima di "allora".
3 -Niente, nota di merito per il corretto uso delle virgolette sulla citazione.
4 - In 4.1 "ideare" non è un verbo appropriato. Al massimo dobbiamo "realizzare".
5 - Forse è meglio dire "agevoli la lettura a persona affette da dislessia".
6 - In 5.3 è meglio mettere l'acronimo tra parentesi dopo "Flexible and Adaptive...", in quanto nelle righe successive vi refirite al motore con l'acronimo.
7 - In 5.5 "viene ritenuto" e non "vengono ritenuto". Poco più avanti manca lo spazio dopo una virgola.

### Conslusioni
Nonostante numerose violazioni delle NdP, il documento presenta una qualità d'esposizione molto buona.

P.S. Se trovate che le correzioni siano troppo precise è perchè ho chiesto l'aiuto di mia sorella, che sa scrivere nel modo più formale e corretto.

**Comment by Scramasax443** [comment]
Ho risolto i problemi segnalati,chiudo l'issue.
