### ISSUE TITLE
Proposta di aggiunta termini in Glossario

### ISSUE THREAD

**Issue by Scramasax443** [CoCodeSWE/Docs#18]
Nella stesura del documento SdF, io e @ntintorri abbiamo notato la mancanza di alcuni termini di cui riteniamo necessaria la presenza nel glossario. 
In allegato un file txt contenente i termini proposti:

[AggiunteGlossarioi.txt](https://github.com/CoCodeSWE/Docs/files/661714/AggiunteGlossarioi.txt)

**Comment by BottCode** [comment]
Ne parliamo al Brainstorming di domani

**Comment by BottCode** [comment]
**Scrivere qui le parole che proponete di inserire nel glossario.
Non allegate file, scrivete direttamente.**

**Comment by Scramasax443** [comment]
da PdQ:
- Plan-Do-Check-Act (PDCA)

**Comment by Scramasax443** [comment]
raspberry pi
Calcolatore implementato su una sola scheda elettronica. L'idea di base è la realizzazione di un dispositivo economico, concepito per stimolare l'insegnamento di base dell'informatica e della programmazione nelle scuole.


python
Linguaggio di programmazione ad alto livello, orientato agli oggetti.


apple watch 
Orologio dotato di funzionalità per dispositivi mobili prodotto da Apple.

cordova
È un framework per lo sviluppo di applicativi per dispositivi mobili.

**Comment by Mou95** [comment]
C++: E' un linguaggio di programmazione orientato agli oggetti, con tipizzazione statica. È stato sviluppato da Bjarne Stroustrup ai Bell Labs nel 1983 come un miglioramento del linguaggio C.

Cloud-based: E' un termine riferito ad applicazioni, servizi o risorse disponibili agli utenti attraverso Internet.

PHP: E' un linguaggio di scripting interpretato, (acronimo di Hypertext Preprocessor) originariamente concepito per la programmazione di pagine web. Attualmente è principalmente utilizzato per sviluppare apllicazioni web lato server.

Microsoft Cortana: E' un software di assistenza e riconoscimento vocale sviluppato da Microsoft.

**Comment by sosssoldi** [comment]
*double token* = Un'autenticazione a due fattori (o autenticazione a più fattori) è un metodo di autenticazione che si basa sull'utilizzo congiunto di due metodi di autenticazione individuale.

*crash* = Il termine crash nel gergo informatico indica il blocco o la terminazione improvvisa, non richiesta e inaspettata di un programma in esecuzione, oppure il blocco completo dell'intero computer.

*freeze* =  L'interruzione temporanea del funzionamento regolare  di un programma in esecuzione, oppure dell'intero computer.

**Comment by sime1** [comment]
Unity è un motore per videogiochi disponibile per diverse piattaforme

Botkit è un insieme di strumenti che fornisce i blocchi fondamentali per la creazione di bot per piattaforme di messaggistica, tra le quali figura anche Slack

OAuth 2.0 è l'evoluzione di OAuth, un protocollo per l'autorizzazione creato originariamente nel 2006.

**Comment by pierz95** [comment]
\parola{Windows Phone}{Famiglia di sistemi operativi per smartphone di Microsoft.}


\parola{HTTPS}{Protocollo per la comunicazione sicura attraverso una rete di computer, il quale è largamente utilizzato su Internet.}

**Comment by sime1** [comment]
On Demand: termine generale che si riferisce a risorse fornite all'utente dopo un'esplicita richiesta

**Comment by BottCode** [comment]
API gateway
Microservizi
Enrollments
Direttive
Continuos Integration
DOM
Adapter

**Comment by pierz95** [comment]
nome di ogni pattern di definizione di prodotto, descrivo velocemente

**Comment by sime1** [comment]
endpoint : è l'url reso disponibile da un servizio per l'accesso ad una funzionalità da parte dei client.
speaker recognition

**Comment by BottCode** [comment]
Rule

**Comment by BottCode** [comment]
Attachment

**Comment by BottCode** [comment]
unix timestamp

**Comment by sime1** [comment]
SNS
base64
webhook?

**Comment by BottCode** [comment]
REST

**Comment by sime1** [comment]
speech to text
text to speech

**Comment by BottCode** [comment]
JWT

**Comment by BottCode** [comment]
Nel contesto API.AI: Intents, Agent, Entities.

**Comment by BottCode** [comment]
Heroku

**Comment by BottCode** [comment]
GUID (Globally Unique Identifier, identificatore unico globale)

**Comment by BottCode** [comment]
broadband e narrowband?

**Comment by BottCode** [comment]
signature? - Edit( from scramasax): non ancora inserito.

**Comment by BottCode** [comment]
URL

**Comment by BottCode** [comment]
sample

**Comment by BottCode** [comment]
Blob

**Comment by BottCode** [comment]
**LE PAROLE PRECEDENTI SONO STATE AGGIUNTE**
# EDIT: NON È UN CAZZO VERO

**Comment by BottCode** [comment]
callback

**Comment by BottCode** [comment]
Payload

**Comment by BottCode** [comment]
machine learning

**Comment by BottCode** [comment]
serverless

**Comment by BottCode** [comment]
single responsibility principle

**Comment by BottCode** [comment]
thorughput

**Comment by BottCode** [comment]
Single sign-on

**Comment by BottCode** [comment]
**LE PAROLE PRECEDENTI SONO STATE AGGIUNTE**
