### ISSUE TITLE
verifica 19-12 NdP 

### ISSUE THREAD

**Issue by sosssoldi** [CoCodeSWE/Docs#19]
Sommario -> Co.Codenel
Indice 3.1.11.1 glLatex
indice 4.1.10.7 si chiama GanttProject con la 'P' maiuscola vedi anche Elenco delle figure 6
2.1.4.3 da completare
2.1.4.6 da decidere
2.1.4.8 da decidere
2.1.4.9 errore di battitura spazio prima della virgola
2.1.5.2 sopra citati -> sopracitati
2.1.5.4 Maiuscole sui punti dell' elenco, design pattern senza g, manca tracciamento delle componenti
3.1.4 glLatex
3.1.5 glLatex più a capo senza motivo
3.1.6.2 quarto punto: attore o autore?
3.1.8.1 Dopo URL ci andrebbe il punto in quanto è l'ultimo elemento di un sottosottoelenco, o no?
3.1.8.2 glLatex
3.1.8.3 vedi 3.1.8.1
3.1.10.2 toglierei il "già" sa di discorso orale
3.1.10.4 manca il';' dop il punto dell' elenco "TipoVerbale". Cambiere la fine del paragrafetto con: "dove nel codice la D viene sostituit dalla S"
3.1.11.1 rivedi macro Latex
3.1.11.3 manca il punto dopo "ecc"
3.2.3.1 in "sta cercando e consiste" cambierei la e con una ","
team è in glossario?
3.2.4.1 il punto 2 credo che il termine "essere" sia in più
3.2.5.3 indice Gulpease in glossario direi
4.1.4.1 manca il punto finale
Telegram in glossario?
4.1.8.2 sul punto esterni alla fine ci va il ; non il lo stesso su script.
4.1.10.7 GanttProject

**Comment by Mou95** [comment]
2.1.4.3 da guardare
Per quanto riguarda le parole da mettere nel glossario o i problemi di glossarizzazione vediamo più avanti.

**Comment by sosssoldi** [comment]
@Mou95 puoi chiuderla se avete sistemato, manca solo la approvazione di @sime1 se non sbaglio
