### ISSUE TITLE
verifica AdR 02-01

### ISSUE THREAD

**Issue by sosssoldi** [CoCodeSWE/Docs#22]
uc1			[rimuoverei il "il" prima di nome e cognome]
uc2.1		[si dice "da lui" o "a lui"?] || ["in base a certi parametri" sembra molto vago se si può cambierei con "prestabiliti" o qualcosa di simili]
uc2.1.1.2	[nel nome mettete "inserimento" mentre nello scenario principale usate il termine "modifica"]
uc2.1.1		[L'amministratore può eliminare dal sistema una direttiva di cui ha i privilegi. ]
uc2.1.4.4	[direttive* nel nome]
uc2.2		[nello scenario principale andrebbe ripetuto "il proprio" anche su cognome a mio parere]
uc5 		["comprendere una comunicazione" non suona benissimo, forse meglio "interpretare"]
uc6 		["attraverso il quale potrà"]
uc9.1.2.2	[su pre e post prima usate di un poi dell']

**Comment by BottCode** [comment]
uc9.1.2.2 Nel sistema possono esistere più amministratori. Proprio per questo motivo la pre e la post sono scritte in quel modo
