### ISSUE TITLE
Verifica PdQ

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#30]
2.1.1.1 non usare acronimo prima di averlo spiegato, è una critica che è stata fatta in passato
2.1.2 riga 2, sostituire inoltre con quindi? oppure "a questo scopo"
2.1.2.1.3 soglia di accettabilità: doppia negazione, sostituire "non più" con "meno"
2.1.2.2 se il secondo punto vale, allora dobbiamo fissare come soglia di accettabilità per i requisiti desiderabili il 100%. vedete voi cosa fare, per me va bene anche così
2.1.2.2.4 di solito, per quanto io sappia, con "copertura dei test" non si intende la percentuale dei test passati, ma la percentuale di codice coperto da test. Potrei sbagliare, ma controllate comunque. Nel caso in cui quello che ho detto sia giusto, i valori per questa metrica vanno bene, altrimenti metteri 90% accettabile e 100% ottimale. Se un test non passa significa che il programma prima o poi crasherà, quindi dobbiamo puntare a passarli tutti. In ogni caso aggiungerei anche la metrica mancante tra le due.

In generale: viene sempre scritto "Riassumendo" prima di presentare le metriche, ma in genere non state riassumendo bensì aggiungendo nuove informazioni, come i valori numerici delle metriche. Forse è il caso di cambiare parola?

**Comment by Scramasax443** [comment]
Ho corretto, chiudo l'issue.
