### ISSUE TITLE
Report attività di verifica SDK 2017-01-7

### ISSUE THREAD

**Issue by BottCode** [CoCodeSWE/Docs#31]
- in 1.1 "un analisi" -> "un'analisi"
- in 2.2 "la piattaforma non del tutto stabile" -> "... non è del tutto ..."
- in 2.2 mancano i due punti all'elenco puntato. Nel secondo punto c'è ancora "-da spiegare cosa sono-". Nel terzo punto avete messo il punto dopo "C", ma non dovrebbe esserci. Il quinto punto è incompleto.
- in 3.1 api.ai potrebbe essere scritto in maiuscolo(guardate qui https://api.ai/about/). Fate voi.
- in 3.1, piccola osservazione sul contenuto(anche se non è ruolo del verificatore): è giusto dire "interazioni sofisticate con il linguaggio naturale"? 
- in 3.2 dovrebbe essere meglio dire "trasformare in linguaggio naturale in dati ...".
- in 4.1 "sviluppato"->"sviluppata", è femminile, giusto? A meno che non vi riferiate ad Echo.
- in 5.2 "dei ambiti"->"degli ambiti"

A fine documento dite che optiamo per api.ai. Quindi alexa che ruolo avrà nel progetto? Inoltre è bene "evidenziare" ciò che scegliamo. Una sotto-sezione 7.1 SDK scelto arebbe l'ideale secondo me.

**Comment by ntintorri** [comment]
Corretti i punti 1.1, 2.2 (l'elenco), 3.1 (è corretto API.AI), 3.2 e 5.2.
Nel 4.1 "sviluppato" si riferisce ad Echo.
2.2 (la piattaforma ecc.) è giusto, non ha bisogno di correzione.
