### ISSUE TITLE
Verifica PdQ 8/1

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#32]
CMM:

  * introduzione, secondo punto: best practiceS, metterei anche tra virgolette ma col glossario forse non serve, il top sarebbe metterlo in italiano
  * A.1 terzo punto, userei "tipologie" al posto di "tipi" ma vedete voi
  * A2 quarto livello, "gestiti" invece di riadattati, aiuta a capire il significato della frase e perchè questo livello è chiamato gestito
  * A2, quinto livello, "sono volti a migliorare continuamente le proprie" con "sono soggetti ad un continuo miglioramento delle proprie"
  
ISO/IEC
  * B1.1 terzo punto: cpcità, "in un determinato contesto" al posto di  "di un determinato contesto" 
PDCA
  * Act: non sono sicuro sull'utilizzo del passato prossimo nella frase "ovvero di strategie che hanno portato miglioramenti", forse meglio usare il presente?
  * frase conclusiva: at-tività

**Comment by Scramasax443** [comment]
Ho corretto,chiudo l'issue
