### ISSUE TITLE
Verifica glossario

### ISSUE THREAD

**Issue by Mou95** [CoCodeSWE/Docs#35]
Finire diario modifiche con le verifiche e l'approvazione. Correggere data redazione

1. Non mi convince come header la prima parola di ogni pagina
2. Cambiare descrizione del modello incrementale
3. Policy manca descrizione
4. Rocket chat--> videochiamata tutto attaccato credo
5. Slack --> scrivere qualcosa riguardo la messaggistica?
6. TvOs --> descrizione inizia con lettera minuscola
7. Uguale watchOs

Mettiamo una pagina per ogni lettera anche se non abbiamo parole?

**Comment by pierz95** [comment]
ho fatto da 2 a 7, manca l'1. falla tu botta perchè non capisco nothing

**Comment by BottCode** [comment]
I dizionari sarebbero fatti così, comunque manco lo avevo notato...era una cosa del template che non avevo mai visto
