### ISSUE TITLE
Approvazione PdQ 10.01

### ISSUE THREAD

**Issue by sosssoldi** [CoCodeSWE/Docs#36]
2.1.1 doppio spazio prima di "Quindi" e credo sia meglio mettere una virgola piuttosto che il punto prima di "Quindi"
2.1.1.1 il secondo "si vuole raggiungere" lo vedo di troppo, potrebbe essere tagliato.
2.1.1.2 "Schedule Variance" perchè cammellata?
2.1.1.3 "Cost Variance" vedi 2.1.1.1 | spendere meno mi sembra molto colloquiale, si riesce a sostituire?
2.1.2.2.5 fose bisognerebbe scrivere "dell'80%"
2.1.2.2.6 vedi sopra | "Breakdown Avoidance" still cammellata
3.2.1 "essre"
aggiungerei best practices sul glossario
A.1 e seguenti credo vadano le maiuscole ad ogni  punto dell'elenco
B manca uno spazio dopo i ":"
B.1.1 userei "la minor quantità di risorse"
B.1.2 vedi B.1.1
C PDCA non so se su Act - Agire  vada al futuro "hanno portato" in "porteranno" 
Da sistemare macro SDK 
Completare le tabelle con le x

**Comment by ntintorri** [comment]
2.1.1 è corretto nel file, penso sia un problema di compilatore.
2.1.1.2, 2.1.1.3 e 2.1.1.6 sono cammellate.
2.1.2.2.5 penso vada bene anche "del 80%".
Corretto: 3.2.1 e B.

Aggiorno:
2.1.1.1 il secondo "si vuole raggiungere" lo vedo di troppo, potrebbe essere tagliato.
2.1.1.3 spendere meno mi sembra molto colloquiale, si riesce a sostituire?
aggiungerei best practices sul glossario
A.1 e seguenti credo vadano le maiuscole ad ogni punto dell'elenco
B.1.1 userei "la minor quantità di risorse"
B.1.2 vedi B.1.1
C PDCA non so se su Act - Agire vada al futuro "hanno portato" in "porteranno"
Da sistemare macro SDK
Completare le tabelle con le x
