### ISSUE TITLE
Verifica AdR 10.01.2016

### ISSUE THREAD

**Issue by sosssoldi** [CoCodeSWE/Docs#37]
2.2 allospite
UCG - scenario principale c'è un ';' dopo Attori e un '.' dopo gli altri
dubbio uc0 se dopo nome e cognome può gia il sistema distinguere se ospite o amm
3.5.6  scenario principale "gliu"
3.6.6. scenario principale due vole il punto 3 e bisogna andare a capo
3.8 UC5 "una chiarimento"
3.10.11 prima usate dati nulli poi dati vuoti
3.11 su scenario principale c'è 1. anche se è uno solo e non un elenco
4 sottoelenco di fonte, credo vadano in grassetto da capitolato  a caso d'uso

non abbiamo gestito password dimenticata, basta mettere che si rivolga al super amministrtore?

credo il temrine direttiva necessita una spiegazione, o la mettiamo sul glossario?

**Comment by sime1** [comment]
effettuate tutte le correzioni, direttiva dobbiamo decidere come comportarci perchè il termina appare con un significato diverso anche nell'analisi degli sdk
