### ISSUE TITLE
Correzione ed evoluzione delle Norme di Progetto

### ISSUE THREAD

**Issue by BottCode** [CoCodeSWE/Docs#38]
Rapporto del docente: _Esiguo il numero di processi considerati e povera, per ampiezza e profondità 
la specifica delle procedure previste a loro supporto. Buona invece la struttura 
e apprezzabile l’alternanza di immagini e testo.
Nel complesso, documento da rivedere._

Le parti mancanti sono:

1. Processo di Qualità (che è di supporto), done 
2. Processo di Configurazione (supporto), done
3. Parte sui test in 2.1.6 codifica
4. strumenti per il testing in 2.1.8 

Bisogna ampliare:

1. Sezione dei processi di supporto, in particolare la parte di Verifica(done) e un po' quella di documentazione(done).
2. Sezione dei processi organizzativi(semi-done, manca l'esposizione sulla procedura di assegnazione e creazione dei task in Asana).

_**--UPDATE 2017-02-17--**_ 
Ho quasi ultimato la correzione, manca solo da migliorare la sezione sui processi organizzativi che non richiederà molto tempo.
Tuttavia bisogna aggiungere alcune cose specifiche della RP, in particolare tutte le cose riguardanti il testing, alcune metriche di qualifica e gli strumenti per valutarle. Ho visto che PragmaDB le traccia e in 2.1.7 l'ho scritto. È necessario discutere di tutto questo con chi si occupa della qualifica.

_**-- UPDATE 2017-03-15 --**_ 
Sarà necessario definire le norme e procedure nell'utilizzo di altri strumenti, quali ad esempio API.AI(come scrivere/inserire gli intents, entities, ecc) e lo stile di codifica per le _promesse_ e _callback_ in javascript e Node.js.

**Comment by BottCode** [comment]
La sezione relativa al processo di Qualità è completa per struttura, ma manca per alcuni contenuti sugli strumenti per valutare le metriche calcolabili da PragmaDB.

**Comment by BottCode** [comment]
Completata sezione processi di configurazione.

**Comment by BottCode** [comment]
Completata sezione Verifica in processi di supporto.

**Comment by BottCode** [comment]
Completata sezione Documentazione in processi di supporto.

**Comment by BottCode** [comment]
**Concluse le correzioni indicate dal docente**

**Comment by BottCode** [comment]
Semi-completata la sezione sui processi organizzativi

**Comment by pierz95** [comment]
Completata la sezione sui processi organizzativi

**Comment by BottCode** [comment]
ReactiveX
