### ISSUE TITLE
Domande

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#43]
chiedere a cardin per due distinti pattern architetturali client-server
chiedere a cardin per package microservizi
package correlati: può un package essere correlato ad un altro package che è ad un livello inferiore (dentro un altro package al suo stesso livello)?
lambda functions e classi/packages
packages intermedi per comunicazione tra componenti lato client
unire i microservizi impostazioni e assistente virtuale?
signal (reception) nei diagrammi di classe
librerie esterne modificate ad hoc
webhook?

**Comment by Mou95** [comment]
- costruttori in uml??
- facade, metodi che sono quasi proxy dobbiamo scrivere che chiamano i metodi della libreria?
- object o JSON??
- servizi esterni come librerie esterne? (diagramma pkg)
- classi interne uml e package
- chain of responsibility
- package con unica classe?
