### ISSUE TITLE
Compiti vari per chi non sa cosa fare

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#46]
- vari livelli grafico
- descrizione librerie esterne per documento DdP (cerca con google bluebirdjs (la utilizziamo per promises, spiegare cosa sono promises), RxJs(usiamo per observer/pbservable), AWS SDK for JavaScript in Node.js(principalmente per accesso a dynamoDB))
- descrizione interfaccia rest swagger + descrizione interfaccia rest in documento [(editor)](http://editor.swagger.io/#!/)
- php per generazione descrizione classi (a partire dal [template](https://github.com/CoCodeSWE/Docs/wiki/template-generazione-classi-latex))
- definizione test
- verifica documenti (AdR, PdQ, DdP)
- TBA

**Comment by ntintorri** [comment]
Verificare anche NdP
