### ISSUE TITLE
Testing lambda

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#47]
[link](https://medium.com/vandium-software/unit-testing-aws-lambda-functions-in-node-js-7ad6c8f5000#.x65w124gq)

**Comment by sosssoldi** [comment]
[Test endpoint RESTful API](https://scotch.io/tutorials/test-a-node-restful-api-with-mocha-and-chai)

**Comment by sime1** [comment]
https://blog.risingstack.com/node-hero-node-js-unit-testing-tutorial/

**Comment by sosssoldi** [comment]
[comandi per Mocha](https://webapplog.com/tdd/)

**Comment by sosssoldi** [comment]
https://www.npmjs.com/package/lambda-local
