### ISSUE TITLE
Ruoli per diario

### ISSUE THREAD

**Issue by Scramasax443** [CoCodeSWE/Docs#63]
In seguito i ruoli da utilizzare nel diario delle modifiche:

in AD:

Andrea Magnan : PdQ (modifica sezioni - no test yet) [AM] , glossario(aggiunta termini) [AM] , verifica verbali interni
Luca Bertolini : PdQ (modifica sezioni - no test yet ) [AM] , verbali interni [AM] , verifica AdR
Mattia Bottaro : AdR (modifica sezioni) [AN], verifica verbali esterni
Mauro Carlin : AdR (modifica sezioni) [AN], verifica NdP
Nicola Tintorri : PdP (analisi rischi per periodo e consuntivo periodo) [RP] ,verbali esterni [RP] , NdP (nuove sezioni riguardo periodo)[AM], approvazione documenti [RP]
Pier Paolo Tricomi : AdR (modifica sezioni) [AN], verifica PdP e glossario
Simeone Pizzi  : AdR (modifica sezioni) [AN] , verifica PdQ

a fine periodo: tutto v2.0.0

in PA:

Andrea Magnan : AdR (modifica sezioni) [AN], verifica PdP e glossario 
Luca Bertolini : glossario(aggiunta termini) [AM] , AdR (modifica sezioni) [AN] , verifica DdP 
Mattia Bottaro : PdP (analisi rischi per periodo e consuntivo periodo) [RP], AdR (modifica sezioni) [AN], approvazione documenti [RP] (tranne DdP, deve essere approvato solo alla fine, cioè il periodo successivo)
Mauro Carlin : DdP (sezione riguardanti la specifica tecnica) [PT] , verifica verbali interni-esterni 
Nicola Tintorri : DdP (sezione riguardanti la specifica tecnica) [PT] , verifica ndP
Pier Paolo Tricomi : DdP (sezione riguardanti la specifica tecnica) [PT] , glossario(aggiunta termini) [AM] , NdP (aggiunta sezioni riguardo periodo) [AM], verbali interni [AM], verifica AdR
Simeone Pizzi : DdP (sezione riguardanti la specifica tecnica) [PT] , NdP (aggiunte sezioni riguardo periodo) [AM] , verbali interni [AM], verifica AdR

a fine periodo: tutto v3.0.0 tranne PdQ: v2.0.0  e DdP: v < 1.0.0

in PD:

Andrea Magnan : PdQ(stesura test + tracciamento) [PT], PdQ(resoconto)[AM],NdP (sezioni riguardo periodo)[AM], verifica NdP, approvazione documenti [RP]
Luca Bertolini : PdP (analisi rischi per periodo e consuntivo periodo) [RP] , DdP(dettaglio) [PT], verifica glossario e AdR, approvazione documenti [RP]
Mattia Bottaro : DdP(dettaglio) [PT], AdR (tracciamento requisiti- test) [AN], verifica PdQ e NdP
Mauro Carlin : glossario [AM], verbali interni [AM], NdP (sezioni riguardo periodo) [AM] , AdR ( tracciamento requisiti- test) [AN], verifica DdP
Nicola Tintorri : AdR (tracciamento requisiti- test) [AN], verifica DdP
Pier Paolo Tricomi : PdQ(stesura test + tracciamento) [PT], DdP(dettaglio) [PT], AdR (tracciamento requisiti- test) [AN], verifica PdP
Simeone Pizzi : DdP(dettaglio)[PT], AdR (tracciamento requisiti- test) [AN] , verifica verbali interni

a fine periodo: tutto v4.0.0 tranne PdQ: v3.0.0 e DdP: v1.0.0

In allegato la versione .txt
[chifa.txt](https://github.com/CoCodeSWE/Docs/files/886463/chifa.txt)

**Comment by BottCode** [comment]
Sicuro che la versione da consegnare della DdP sia 1.0.0 e non superiore?

**Comment by Scramasax443** [comment]
Cito l'esito RP fellowship: "Sfuggono i motivi per cui il documento sia già in versione 2.0 al primo 
rilascio esterno formale."
