### ISSUE TITLE
cose da sistemare

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#72]
* ConversationAction Observable, subject e observer su pragma
* pattern flux ([link](https://github.com/facebook/flux/tree/master/examples/flux-concepts))
* React.Component su pragma, React come libreria esterna in diagramma client, React in tecnologie utilizzate
* controllare questione Client Side Discovery, se quello che facciamo può essere configurato come un DAO togliere i riferimenti a pattern CSD.
* WebhookServive (l'interfaccia), il parametro event del metodo è da descrivere meglio, spiegando il formato della richiesta che si riceve come è fatto nell'altro parametro [link a documentazione](https://docs.api.ai/docs/query#response)
* per le classi che dicevamo di aggiungere (quelle al momento definite solo in JSON) non ho fatto, se qualcuno riesce ora metto i dump del db su telegram, altrimenti faremo in seguito o non faremo

Classi aggiunte su pragma da aggiungere ai disegni:
* ConversationDispatcher
* ConversationView
* MessageStore
* ErrorSubject
* ConversationAction
* penso siano queste, è il caso di controllare però..

**Comment by BottCode** [comment]
Credo manchi la classe ActionSubject, usata in ConversationAction (e relativi observer/observable)

**Comment by BottCode** [comment]
Dove vanno le classi ConversationAction Observable, subject e observer? IMmagino siano correlate con conversationApp

**Comment by BottCode** [comment]
Come collegare React nel disegno?
Perchè React.component in Pragma che è esterna?
ErrorSubject dova va?

**Comment by ntintorri** [comment]
Da fare:
VocalAPI (aggiunti ErrorObservable)

VAResponsePromise (ApiAiVAAdapter)

StringObservable [Back-end::Users::<>VocalLoginModule createUser()].
SRUserObservable.
Aggiunti ErrorObservable
Exception
cambiare descrizione degli observer del client
+ register(name: String, pkg: ApplicationPackage): boolean

React libreria

Aggiungere un paragrafo per la grafica

SIstemare Observer lato Client (boolean in next).

**Comment by sime1** [comment]
* Credo manchi la classe ActionSubject, usata in ConversationAction (e relativi observer/observable)

non ho capito di cosa parli

* Dove vanno le classi ConversationAction Observable, subject e observer? IMmagino siano correlate con conversationApp

vengono utilizzate direttamente o indirettamente da conversationApp, se guardi le classi nuove vedi di preciso chi le usa, comunque sono sempre solita descrizione di observer/observable/subject

* Come collegare React nel disegno?

libreria esterna

* Perchè React.component in Pragma che è esterna?

perchè la view della conversation eredita da questa e dobbiamo scriverlo

* ErrorSubject dova va?

Nello stesso package di Observer e Observable relativi
