### ISSUE TITLE
Sass in NdP

### ISSUE THREAD

**Issue by Scramasax443** [CoCodeSWE/Docs#75]
Di seguito la sezione dedicata a Sass da mettere nella sezione Codifica nelle NdP, da controllare e integrare.

\paragraph{Sass}
 Per la creazione dei fogli di stile viene usato Sass, un linguaggio di scripting interpretato in CSS. Viene usato per semplificare la lettura e scrittura di file CSS. In particolare, permette:
 \begin{itemize}
 \item la definizione di variabili, per il riutilizzo di informazioni;
\item l'annidamento dei selettori;
\item l'ereditarietà dei selettori;
\item la possibilità di utilizzo di operatori matematici;
\item la possibilità di includere file Sass all'interno di altri file Sass che il browser interpreterà come un singolo file CSS, aumentandone la modularità; 
\end{itemize}
(possibile sezione dedicata alla procedura di utilizzo?)

**Comment by sime1** [comment]
Questa sezione è quella del DdP, quella in NdP non deve descrivere la tecnologia così in dettaglio e soprattutto non deve essere uguale a quella messa in DdP. Quello che ci interessa mettere nelle norme è, siccome sass ha due sintassi ben distinte, una sezione dove chiariamo che la sintassi che utilizziamo è quella scss, che è di fatto un'estensione del linguaggio css. Utilizzo non serve, al massimo se vogliamo possiamo descrivere una procedura di compilazione in locale, nel caso si voglia testare che il codice scss scritto compili senza generare errori.
