### ISSUE TITLE
Possibile utilizzo asana

### ISSUE THREAD

**Issue by sime1** [CoCodeSWE/Docs#8]
siccome i termini utilizzati da asana sono gli stessi nostri ma con un significato
diverso, ho cercato di segnare con il grassetto le volte che ho scritto un termine 
al cui ho dato lo stesso significato datogli da asana

Asana ha una struttura gerarchica che dall'alto verso il basso è: **Team** -> **Progetti** -> **compiti**.
Il **team** è formato da una serie di persone, le quali sono divise in sottogruppi, ognuno con
un **progetto** diverso. Una persona può appartenere a più **progetti**. Mettendolo in relazione 
coi termini che utilizzaimo noi, abbiamo in pratica che **Team** = Progetto, **Progetto** = Task,
**compiti** = compiti all'interno del task. Un possibile metodo di utilizzo è il 
seguente: creaiamo un  **progetto** generale (l'attuale **progetto** AtAVi) dove segnamo milestones nostre e scadenze esterne (Revisioni di progetto, eventuali scadenze imposte dall'azienda, ..).
Per ogni task utilizziamo un **progetto** separato, col nome del task da eseguire (es. 
stesura piano di progetto). Le persone incaricate di svolgere quel particolare compito 
si aggiungeranno al **progetto**. Alla creazione del **progetto** esso viene diviso
in una serie di sottocompiti, i quali verranno scritti come **task** sulla "bacheca" del 
progetto, senza essere ancora assegnati a nessuno. I membri del **progetto** si occuperanno
di prendere un **task** a testa e di portarlo a termine, assegnandolo a sè stessi. Ogni
volta che un membro porta a termine un **task**, ne prende un altro. Chiaramente i task
saranno decisi dal/insieme al responsabile in carica alla creazione del **progetto**, il quale
responsabile dovrà anche controllare la assegnazione dei compiti. A tale scopo, 
il responsabile sarà iscritto a tutti i compiti di tutti i progetti (probabilmente con l'account del gruppo,
per facilitare il passaggio da un responsabile al sucessivo). Le varie colonne
presenti nella bacheca possono essere utilizzate sia per dividere i **progetti** in
"moduli", in modo che un modulo sia gestito da un'unica persona (in questo caso però è 
da rivedere il funzionamento del metodo di assegnazione dei **task**), o anche per segnare 
milestones interne al **progetto**.

**Comment by BottCode** [comment]
Va bene, chiaro. Concordo sul fatto che il responsabile dovrà usare l'account di gruppo per facilitare le rotazioni di ruolo.

**Comment by Mou95** [comment]
Simeone re del mondo circa subito. D'accordo su tutto (y)
