### ISSUE TITLE
Verifica15/12 NdP

### ISSUE THREAD

**Issue by sosssoldi** [CoCodeSWE/Docs#9]
Edit: Errore mio, ho verificato la penultima versione e non l' ultima. 

Verbale: 2.3 S1.3 "colte"

NdP:
Colore Indice
1.2 "l'interessato" è ambiguo
1.4.2 vuoto
2.1.1 "produrre il prodotto"
Proponente in glossario, proponenti no?
2.1.4.5 Postcondizione?
3.1.2 e 3.1.3 ripetitive
3.1.6.2 "i diario" "seconda" attore o autore?
3.1.8.3 "usato prima 4 e poi 2"
3.1.10.1 "Responsabiledi"
4.1.4.2 "monioraggio"

**Comment by BottCode** [comment]
1 - Non capisco la correzione su S1.3. Cosa non va bene in quell'espressione? Con cosa la cambio?
2 - In NdP 1.2 ho preso il testo redatto dalla Zero12 nella loro presentazione, di mio non c'è nulla. Devo cambiarlo lo stesso? Con cosa?
3 - 3.1.8.3, non capisco.

**Comment by sime1** [comment]
vi aggiungo il mio feedback, fatto tenendo conto anche delle funzionalità fornite da PragmaDB: 

* PragmaDB non fornisce la distinzione tra Attori primari e secondari negli use cases. Vogliamo eliminarla anche noi oppure voglieamo implementarla all'interno del sistema?
* Nei requisiti a mio parere ci sono più cose di cui tenere traccia: rapporti padre/figlio tra diversi requisiti, stato di implementazione, importanza (obbligatorio, desiderabile, opzionale). PragmaDB permette di tenere traccia di questi aspetti, e volendo permette anche di tenere traccia dell'accettazione del requisito, ma quella non è così indispensabile forse.
* Per quanto riguarda lo stile di programmazione, le norme che abbiamo definito sono davvero poche, forse è il caso di vedere se rimuoverle dal documento temporaneamente oppure se definirne altre. Se ne scriviamo due messe in croce finisce per sembrare che le abbiamo buttate là tanto per fare secondo me. In ogni caso vedete voi.
* Nella sezione 3.1.4.1 è descritto un processo decisamente diverso da quello seguito da noi per l'approvazione dei documenti; visto che Tullio ha detto più volte che la verifica non deve essere fatta alla fine, e visto che noi non la facciamo alla fine, dovremmo metterlo in evidenza. Nei diagrammi di gannt che finiranno nel piano di progetto abbiamo deciso di far partire e terminare le fasi di verifica un giorno dopo l'inizio delle rispettive fasi. Possiamo decidere anche in modo diverso o con tempi diversi, ma è importante far vedere che non verifichiamo solo alla fine.
* 3.1.8.4 due volte le virgolette in tutti gli elementi dell'elenco puntato
* in genere mi sembra che manchino gli spazi dopo le scritte "LATEX" un po' dappertutto, ma su questo potrei sbagliarmi io
 * 3.2.4.1 primo punto della lista, verificatoredovrà, e punto successivo pure
* 4.1.6.1 l'ultima frase, incontri interni e non esterni penso
* Repository, al momento usiamo solo un repository ma ne utilizzeremo almeno un altro, l'amministratore ha creato l'account github che conterrà le varie repository che verranno utilizzate.
rinominate anche il paragrafo sulla struttura per specificare che si riferisce unicamente alla struttura del repository dei documenti
* 4.1.8.3 cambiate commitare con effettuare la commit, il professore ha fatto capire più volte che non ama le parole inglese italianizzate.

tenete conto che ho letto una volta sola il documento e può essere che non abbia capito qualcosa, ho scritto comunque tutto quello che mi creava dubbi per essere sicuro.

**Comment by sosssoldi** [comment]
1.4.2 sistemare punteggiatura e trattinatura
Manca 2.1.5 
2.1.5.3 prima Specifica tecnica, poi Specifica Tecnica || Prodotto maiuscolo
2.1.5.4 da decidere Tracciamento componenti
2.1.5.5 da decidere Tracciamento classi
2.1.7.2 decidere PragmaDB
3.1.8.2 "LATEXcreato"
3.1.8.3 "utilizzando, utilizzando, usando"
3.1.10.2 "Responsabiledi"
3.1.10.3 Cambierei "debba generare" con "generi"
3.1.11.1 "Latexoffre"
3.1.11.2 "oltre ad integrare un compilatore" || "latexviene
3.2.1 togliere barra da screen TexMAker
3.2.3.1 spazio prima della parentesi
-- issue tracking --
3.2.4 "ai quali" "in nel"
3.2.4.1 controlla gli spazi dopo le macro
4.1.5.1 "Google Hangouts"
4.1.5.2 spazio prima del punto dopo la macro della mail
4.1.6.1 cambierei "uno tra gli" con "uno degli"
4.1.10.2 manca il punto a fine frase

**Comment by Mou95** [comment]
@sime1  aggiorno il paragrafo di approvazione di un documento, per il resto vediamo come fare io e @BottCode . Thanks

**Comment by sosssoldi** [comment]
@sime1 secondo me una volta che cominceremo a scrivere UML ci renderemo conto se usare o no gli attori secondari.

**Comment by Mou95** [comment]
Ho corretto la maggior parte delle cose, per le decisioni da prendere aspetto di fare con @BottCode

**Comment by BottCode** [comment]
Io e @Mou95 sosteniamo le seguenti cose:

_Segnalazioni di @sime1_ 

**PragmaDB**
 sarebbe utile distinguere anche tra attori primari e secondari. Poi se è una modifica troppo "onerosa" possiamo anche correggere a mano il grafico risultante, non crediamo sia un problema di troppo.
In ogni caso, è bene far distinzione tra attori primari e secondari.
**Requisiti dei casi d'uso**
Potresti spiegare meglio cosa intendi per rapporti padre-figlio e stato di implementazione?
Pensavamo, se possibile, di includere tutte queste informazioni nel codice identificativo.
Ad esempio il requisito 1.1i-o potrebbe dire che il requisito è figlio del requisito 1, che è implementato e che è opzionale(I gruppi di riferimento hanno adottato questa strategia).
**Stile di programmazione**
Concordiamo, allora scriviamo che verranno decise in seguito.
**Processo di approvazione**
Concordiamo, lo abbiamo corretto in maniera che sia coerente col nostro operato.


Per il resto abbiamo corretto tutto, comprese le segnalazioni di @sosssoldi.

**Comment by sime1** [comment]
Per PragmaDB il problema non è il grafico ma la tabella, l'uml in realtà non fa distinzione tra attori primari e secondari. In ogni caso il punto è ugualmente valido, vedrò se è possibile/facile la modifica e vi aggiornerò.
Per quanto riguarda i requisiti sono d'accordo sul fatto che l'id debba rispecchiare la tipologia e la "discendenza" di un requisito, ma così facendo stiamo comunque tenendo traccia di queste cose, quindi scriviamolo pure. Aggiungo che PragmaDB genera un ID del tipo RFO1.1, dove F indica la tipologia, O la priorità ed il numero la discendenza, quindi magari basiamoci su questo. In ogni caso ho appena visto che la modifica dei requisiti è buggata, quindi visto che comunque ci sarà da metterci mano anche se decidiamo diversamente non dovrebbe essere troppo un problema.

**Comment by BottCode** [comment]
Perfetto, allora se le modifiche a PragmaDB risultano banali falle pure, altrimenti non perderci troppo tempo.
Questo documento sembra ormai essere completo, attendiamo il prossimo report di verifica.
Mancano solo da stabilire i codici id per i casi d'uso e i requisiti: nel prossimo brainstorming sarà bene deciderli, anche in base a quanto hai detto su PragmaDB.
